# Generated by Django 4.1.5 on 2023-01-10 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=12, unique=True, verbose_name='CPF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('editora', models.CharField(max_length=50, verbose_name='Editora')),
                ('edicao', models.IntegerField(verbose_name='Edição')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Retirada')),
                ('data_entrega', models.DateField(verbose_name='Data de Entrega')),
                ('dias_atraso', models.IntegerField(verbose_name='Dias de Atraso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente', verbose_name='Cliente')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.livro', verbose_name='Livro')),
            ],
        ),
    ]
