# Generated by Django 4.1.5 on 2023-01-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=12, unique=True, verbose_name='CPF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('editora', models.CharField(max_length=50, verbose_name='Editora')),
                ('edicao', models.IntegerField(default=1, verbose_name='Edição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(verbose_name='Data de Retirada')),
                ('data_entrega_prevista', models.DateField(verbose_name='Previsão Entrega')),
                ('data_entrega', models.DateField(verbose_name='Entrega')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente', verbose_name='Cliente')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['cliente'],
            },
        ),
    ]
