# Generated by Django 4.1.5 on 2023-01-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='devolvido',
        ),
    ]
