# Generated by Django 4.1.5 on 2023-01-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_livro_observacao_alter_livro_edicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
    ]
