# Generated by Django 4.1.5 on 2023-01-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_emprestimo_devolvido'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='devolvido',
            field=models.BooleanField(blank=True, default=False, verbose_name='Devolvido'),
        ),
    ]
