# Generated by Django 4.1.5 on 2023-01-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_emprestimo_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateField(verbose_name='Data de Retirada'),
        ),
    ]
